# Generated by Django 6.0.7 on 2026-07-24 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "m_support_domains",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Engagement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("company_size_employees", models.IntegerField(blank=True, null=True)),
                ("dev_org_size", models.IntegerField(blank=True, null=True)),
                ("period_start", models.CharField(blank=True, max_length=7)),
                ("period_end", models.CharField(blank=True, max_length=7)),
                ("position", models.CharField(blank=True, max_length=100)),
                ("overview", models.TextField(blank=True)),
                ("responsibilities", models.TextField(blank=True)),
                ("tech_stack", models.JSONField(blank=True, default=list)),
                ("challenges", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "t_engagements",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("speed", "速度改善"),
                            ("cost", "コスト削減"),
                            ("quality", "品質向上"),
                            ("ops", "運用改善"),
                            ("incident", "障害削減"),
                            ("release", "リリース改善"),
                            ("review", "レビュー体制改善"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("metric_before", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("metric_after", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("metric_unit", models.CharField(blank=True, max_length=30)),
                ("metric_delta_pct", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="careers.engagement",
                    ),
                ),
            ],
            options={
                "db_table": "t_achievements",
            },
        ),
        migrations.CreateModel(
            name="EngagementUrl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=500)),
                ("label", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="urls", to="careers.engagement"
                    ),
                ),
            ],
            options={
                "db_table": "t_engagement_urls",
            },
        ),
        migrations.CreateModel(
            name="EngagementDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relevance", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_links",
                        to="careers.engagement",
                    ),
                ),
                (
                    "support_domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_links",
                        to="careers.supportdomain",
                    ),
                ),
            ],
            options={
                "db_table": "r_engagement_domains",
                "unique_together": {("engagement", "support_domain")},
            },
        ),
    ]
