# Generated by Django 6.0.7 on 2026-07-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='contract_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='engagement',
            name='narrative',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='engagement',
            name='phases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='engagement',
            name='tech_categorized',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
