# Generated by Django 6.0.7 on 2026-07-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='tech_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
