# Generated by Django 6.0.7 on 2026-07-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_engagement_tech_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='manual_skills',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
