# Generated by Django 6.0.7 on 2026-07-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_engagement_manual_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='tech_versions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
