# Generated by Django 6.0.7 on 2026-07-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("careers", "0006_engagement_tech_versions"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagement",
            name="architecture",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
