# Generated by Django 6.0.7 on 2026-08-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0007_engagement_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='project_key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
