# Generated by Django 6.0.7 on 2026-08-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0008_engagement_project_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
