# Generated by Django 6.0.7 on 2026-08-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0009_engagement_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='local_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
