# Generated by Django 6.0.7 on 2026-08-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0010_engagement_local_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='agent',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='engagement',
            name='client',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='engagement',
            name='sier',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
