# Generated by Django 6.0.7 on 2026-08-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0011_engagement_agent_engagement_client_engagement_sier'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='engagement_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='engagementurl',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
