# Generated by Django 6.0.7 on 2026-08-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0012_engagement_engagement_type_engagementurl_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='local_paths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
