# Generated by Django 6.0.7 on 2026-07-24 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("careers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("gemini", "Gemini")], default="openai", max_length=20
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("model", models.CharField(default="gpt-4o-mini", max_length=100)),
                ("is_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "m_user_ai_configs",
            },
        ),
        migrations.CreateModel(
            name="AiGenerationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("model", models.CharField(blank=True, max_length=100)),
                ("success", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "t_ai_generation_logs",
                "indexes": [models.Index(fields=["user", "created_at"], name="t_ai_genera_user_id_2059fb_idx")],
            },
        ),
        migrations.CreateModel(
            name="DomainStatement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("priority", models.IntegerField(default=0)),
                ("body", models.TextField(blank=True)),
                ("char_count", models.IntegerField(default=0)),
                ("source_engagement_ids", models.JSONField(blank=True, default=list)),
                ("ai_model", models.CharField(blank=True, max_length=100)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "support_domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statements",
                        to="careers.supportdomain",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domain_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "t_domain_statements",
                "ordering": ["priority"],
                "unique_together": {("user", "support_domain")},
            },
        ),
    ]
