# Generated by Django 6.0.7 on 2026-07-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiconfig",
            name="model",
            field=models.CharField(default="gemini-2.5-flash", max_length=100),
        ),
        migrations.AlterField(
            model_name="aiconfig",
            name="provider",
            field=models.CharField(
                choices=[("gemini", "Gemini"), ("claude", "Claude"), ("openai", "OpenAI")],
                default="gemini",
                max_length=20,
            ),
        ),
    ]
