# Generated by Django 6.0.7 on 2026-07-26 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CognitoLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cognito_sub", models.CharField(max_length=64, unique=True, verbose_name="Cognito sub")),
                (
                    "provider",
                    models.CharField(
                        choices=[("cognito", "Cognito (Email/Password)"), ("google", "Google")],
                        default="cognito",
                        max_length=20,
                        verbose_name="認証プロバイダー",
                    ),
                ),
                (
                    "cognito_email",
                    models.EmailField(blank=True, default="", max_length=254, verbose_name="Cognito email"),
                ),
                ("last_signed_in_at", models.DateTimeField(blank=True, null=True, verbose_name="最終ログイン日時")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cognito_links",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cognito 紐付け",
                "verbose_name_plural": "Cognito 紐付け",
                "db_table": "m_cognito_links",
                "indexes": [models.Index(fields=["cognito_email"], name="m_cognito_l_cognito_aac4e4_idx")],
            },
        ),
        migrations.CreateModel(
            name="UserAllowedEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="許可 email")),
                ("label", models.CharField(blank=True, default="", max_length=100, verbose_name="ラベル")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="作成日時")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allowed_emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "許可 email",
                "verbose_name_plural": "許可 email",
                "db_table": "m_user_allowed_emails",
                "indexes": [models.Index(fields=["user"], name="m_user_allo_user_id_1ec9e9_idx")],
            },
        ),
    ]
